# AmCat

version: '2'
services:
  postgresqlData:
    image: busybox
    volumes:
      - /var/lib/postgresql

  postgresql:
    image: postgres
    #restart: always
    volumes_from:
      - postgresqlData
    env_file:
      - ./postgres/postgres.env
    depends_on:
      - postgresqlData
    expose:
      - 5432

  elasticsearchData:
    image: busybox
    volumes:
      - /usr/share/elasticsearch/data

  elasticsearch:
    image: cogfor/amcat-elasticsearch
    build: ./elastic
    #restart: always
    volumes_from:
      - elasticsearchData
    expose:
      - 9200
      - 9300

  logstash:
    image: logstash
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    volumes:
      - ./logstash/config:/etc/logstash/conf.d
    ports:
      - 5000:5000
    links:
      - elasticsearch

  kibana:
    image: kibana:4.1
    #restart: always
    ports:
      - 5601:5601
    environment:
      - NODE_OPTIONS=--max-old-space-size=300
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    links:
      - elasticsearch

  rabbitmq:
    image: rabbitmq
    expose:
      - 5671

  amcat:
    image: cogfor/amcat:3.4
    build: ./amcat
    #restart: always
    command: bash -c "service rabbitmq-server start; sleep 5; python -m amcat.manage runserver 0.0.0.0:8000"
    env_file:
      - ./amcat/amcat.env
    depends_on:
      - postgresql
      - elasticsearch
      - rabbitmq
      - logstash
    links:
      - postgresql
      - elasticsearch
      - rabbitmq
      - logstash
    ports: 
      - 8000:8000
      - 443
      - 80

  amcat-scraping:
    image: cogfor/amcat-scraping
    build: ./amcat-scraping
    depends_on:
      - amcat
    links:
      - amcat
